# Generated by Django 6.0.2 on 2026-05-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="fecha y hora de creación",
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="fecha y hora de la última modificación",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "phone_prefix",
                    models.CharField(max_length=10, unique=True, verbose_name="lada"),
                ),
                (
                    "iso_code_alpha2",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        unique=True,
                        verbose_name="código de dos letras",
                    ),
                ),
                (
                    "iso_code_alpha3",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        null=True,
                        unique=True,
                        verbose_name="código de tres letras",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="imagen"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="está activo?"),
                ),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="fecha y hora de creación",
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="fecha y hora de la última modificación",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="abreviatura",
                    ),
                ),
                ("symbol", models.CharField(max_length=120, verbose_name="símbolo")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="está activo?"),
                ),
            ],
            options={
                "verbose_name": "Divisa",
                "verbose_name_plural": "Divisas",
                "ordering": ["-id"],
            },
        ),
    ]
