# Generated by Django 6.0.2 on 2026-05-07 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrative_division", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario del responsable de la creación",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario del responsable de la ultima modificación",
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario del responsable de la creación",
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario del responsable de la ultima modificación",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="countries",
                to="administrative_division.currency",
                verbose_name="divisa",
            ),
        ),
    ]
