# Generated by Django 6.0.2 on 2026-05-07 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrative_division", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="fecha y hora de creación",
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="fecha y hora de la última modificación",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="nombre"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="apellidos"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de nacimiento"
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="carnet de identidad",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="correo electrónico",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="teléfono"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="imagen"
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        blank=True,
                        choices=[("ES", "Español"), ("EN", "Inglés")],
                        default="ES",
                        max_length=2,
                        null=True,
                        verbose_name="idioma",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="hora y fecha de registro"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="está activo?"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="está verificado?"),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="está bloqueado?"),
                ),
                (
                    "last_logged_device",
                    models.CharField(
                        blank=True,
                        choices=[("WE", "Web"), ("AN", "Android"), ("IO", "iOS")],
                        max_length=2,
                        null=True,
                        verbose_name="tipo del dispositivo del último registro",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MA", "Masculino"),
                            ("FE", "Femenino"),
                            ("OT", "Otro"),
                            ("UN", "Sin especificar"),
                        ],
                        default="UN",
                        max_length=2,
                        verbose_name="sexo",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="es staff?"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False, verbose_name="es super usuario?"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="administrative_division.country",
                        verbose_name="país",
                    ),
                ),
                (
                    "country_phone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="country_phone_users",
                        to="administrative_division.country",
                        verbose_name="lada",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario del responsable de la creación",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario del responsable de la ultima modificación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False, verbose_name="es administrador?"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="es staff?"),
                ),
                (
                    "required_country",
                    models.BooleanField(default=False, verbose_name="requiere país?"),
                ),
                (
                    "slug_key",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GEN", "General"),
                            ("MAI", "Mantenimiento"),
                            ("SUP", "Soporte"),
                        ],
                        default="GEN",
                        max_length=3,
                        null=True,
                        verbose_name="clave",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        default="",
                        max_length=100,
                        unique=True,
                        verbose_name="clave identificadora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="GeneralAdmin",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "is_active_rol",
                    models.BooleanField(
                        default=False, verbose_name="tiene rol activo?"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("user.user",),
        ),
    ]
