# Generated by Django 6.0.2 on 2026-05-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("user_permission", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="roles",
                to="user_permission.userpermission",
                verbose_name="permisos",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                related_name="users", to="user.role", verbose_name="roles"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("country_phone", "phone_number")},
        ),
    ]
