# Generated by Django 6.0.2 on 2026-05-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="dni",
        ),
    ]
