# Generated by Django 6.0.2 on 2026-05-07 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario del responsable de la creación",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="fecha y hora de creación"
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario del responsable de la ultima modificación",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="last_modified_date",
            field=models.DateTimeField(
                auto_now=True,
                null=True,
                verbose_name="fecha y hora de la última modificación",
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario del responsable de la creación",
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="fecha y hora de creación"
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario del responsable de la ultima modificación",
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="last_modified_date",
            field=models.DateTimeField(
                auto_now=True,
                null=True,
                verbose_name="fecha y hora de la última modificación",
            ),
        ),
    ]
