# Generated by Django 6.0.2 on 2026-05-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0002_choice_created_by_choice_created_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={
                "ordering": ["-id"],
                "verbose_name": "Elección",
                "verbose_name_plural": "Elecciones",
            },
        ),
        migrations.AlterModelOptions(
            name="vote",
            options={
                "ordering": ["-id"],
                "verbose_name": "Voto",
                "verbose_name_plural": "Votos",
            },
        ),
        migrations.RemoveField(
            model_name="vote",
            name="user_identifier",
        ),
        migrations.AddField(
            model_name="vote",
            name="user",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="usuario"
            ),
        ),
    ]
