# Generated by Django 6.0.2 on 2026-05-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0003_alter_choice_options_alter_vote_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="user",
            new_name="user_identifier",
        ),
    ]
