# Generated by Django 6.0.2 on 2026-05-07 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha y hora"
                    ),
                ),
                ("log", models.TextField(blank=True, null=True, verbose_name="evento")),
                (
                    "request",
                    models.JSONField(blank=True, null=True, verbose_name="solicitud"),
                ),
                (
                    "response",
                    models.JSONField(blank=True, null=True, verbose_name="respuesta"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="código"
                    ),
                ),
            ],
            options={
                "verbose_name": "Aplicación de evento",
                "verbose_name_plural": "Aplicación de eventos",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host_url",
                    models.CharField(
                        default="https://django-template.com.mx/",
                        max_length=120,
                        verbose_name="ruta del host",
                    ),
                ),
                (
                    "push_url",
                    models.CharField(
                        default="https://push-template.com/push",
                        max_length=120,
                        verbose_name="ruta del push",
                    ),
                ),
                (
                    "register_url",
                    models.CharField(
                        default="https://register-template.com/register",
                        max_length=120,
                        verbose_name="ruta del registro",
                    ),
                ),
                (
                    "event_url",
                    models.CharField(
                        default="https://event-template.com.mx/event",
                        max_length=120,
                        verbose_name="ruta del evento",
                    ),
                ),
                (
                    "faq",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pdf",
                        verbose_name="fichero de preguntas más frecuentes",
                    ),
                ),
                (
                    "terms_conditions",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pdf",
                        verbose_name="fichero de términos y condiciones",
                    ),
                ),
                (
                    "privacy_policy",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pdf",
                        verbose_name="fichero de la política de privacidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración",
                "verbose_name_plural": "Configuraciones",
            },
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        verbose_name="identificador del objeto"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("DE", "Objeto de eliminación de usuario"),
                            ("CR", "Objeto de creación de usuario"),
                            ("MD", "Objeto de modificación de usuario"),
                        ],
                        max_length=512,
                        verbose_name="tipo de evento",
                    ),
                ),
                (
                    "event_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha y hora del evento"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_type_logs",
                        to="contenttypes.contenttype",
                        verbose_name="tipo de contenido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-event_date"],
            },
        ),
    ]
