# Generated by Django 6.0.2 on 2026-05-07 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="fecha y hora de creación",
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="fecha y hora de la última modificación",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        max_length=120, verbose_name="nombre de la acción"
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="clave identificadora"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="está activo?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario del responsable de la creación",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario del responsable de la ultima modificación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acción del permiso",
                "verbose_name_plural": "Acciones de los permisos",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PermissionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="fecha y hora de creación",
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="fecha y hora de la última modificación",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True, max_length=120, null=True, verbose_name="nombre"
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="clave identificadora"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="está activo?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario del responsable de la creación",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario del responsable de la ultima modificación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de permiso",
                "verbose_name_plural": "Tipos de permisos",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="fecha y hora de creación",
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="fecha y hora de la última modificación",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="nombre"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="descripción"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="está activo?"),
                ),
                (
                    "actions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_permissions",
                        to="user_permission.permissionaction",
                        verbose_name="Acciones permitidas",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario del responsable de la creación",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario del responsable de la ultima modificación",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_permissions",
                        to="user_permission.permissiontype",
                        verbose_name="Tipo de permiso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso de usuario",
                "verbose_name_plural": "Permisos de usuarios",
                "ordering": ["-id"],
            },
        ),
    ]
